Add friends likes
GlebInside/filmorate pull request #2
Opened 2022-05-14 09:28 UTC by GlebInside

2022-05-16 20:40 UTC, kukolev requested changes

2022-05-16 20:40 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private void addFilms(int count) {
Метод нигде не используется. Неиспользуемый код нужно убирать, чтобы не отвлекал или где-то применить метод, если он нужен.

2022-05-16 20:40 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    UserStorage userStorage;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-05-16 20:40 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private void createUsers(int n) {
Метод нигде не используется. Неиспользуемый код нужно убирать, чтобы не отвлекал или где-то применить метод, если он нужен.

2022-05-16 20:40 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private Film addNewFilm(int n) {
Метод нигде не используется. Неиспользуемый код нужно убирать, чтобы не отвлекал или где-то применить метод, если он нужен.

2022-05-16 20:40 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        return film;
Сейчас код возвращает тот-же объект, что и пришел на вход при вызове метода. Это не имеет смысла. Лучше возвращать объект, который будет записан с уже присвоенным id.

2022-05-16 20:40 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        System.out.println("started");
Вместо вывода в консоль лучше использовать логгер, т.к. это позволит гибче работать с настройками логирования.

2022-05-16 20:40 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        userStorage.addUser(user);
Сейчас код возвращает тот-же объект, что и пришел на вход при вызове метода. Это не имеет смысла. Лучше возвращать объект, который будет записан с уже присвоенным id.

2022-05-16 20:40 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +@Slf4j
Не реализовано логирование в методах. Необходимо реализовать.

2022-05-16 20:40 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            log.error("User " + user + " is in your friends list already");
При логировании лучше использовать возможности библиотеки и пользоваться плейсхолдерами `{}` вместо конкатенации строк. Лучше так: `log.warn("Some warning text for {}", val)` вместо `log.warn("Some warning text for " + val)`. Так код смотрится проще и не происходит лишняя конкатенация строк, если лог не будет напичатан.

2022-05-16 21:48 UTC, GlebInside commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private void addFilms(int count) {
Удалён

2022-05-16 21:48 UTC, GlebInside commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    UserStorage userStorage;
Удалено

2022-05-16 21:48 UTC, GlebInside commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private void createUsers(int n) {
Удалён

2022-05-16 21:48 UTC, GlebInside commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private Film addNewFilm(int n) {
Удалён

2022-05-16 21:48 UTC, GlebInside commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        return film;
Возвращает фильм с присвоенным id

2022-05-16 21:48 UTC, GlebInside commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        System.out.println("started");
Используется логгер

2022-05-16 21:48 UTC, GlebInside commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        userStorage.addUser(user);
Возвращает юзера с присвоенным id

2022-05-16 21:48 UTC, GlebInside commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +@Slf4j
Логирование реализовано

2022-05-16 21:48 UTC, GlebInside commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            log.error("User " + user + " is in your friends list already");
Логирование исправлено

2022-05-17 14:44 UTC, kukolev approved these changes

2022-05-23 18:03 UTC, merged