add new diagram
GlebInside/filmorate pull request #5
Opened 2022-05-23 18:31 UTC by GlebInside

2022-05-25 21:35 UTC, kukolev requested changes

2022-05-25 21:35 UTC, kukolev commented on Queries.txt
> +Get top 10 films by likes:
На схеме нет информации о типах связи: 1 к 1, 1 ко многим и т.п. Необходимо добавить эту информацию.

Поле films.description лучше ограничить в 200 символов, т.к. на это есть валидация.

2022-05-26 19:52 UTC, GlebInside commented on Queries.txt
> +Get top 10 films by likes:
Исправлено

2022-05-26 22:40 UTC, kukolev approved these changes

2022-06-01 17:27 UTC, merged