add DB
GlebInside/filmorate pull request #8
Opened 2022-06-02 11:29 UTC by GlebInside

2022-06-05 08:28 UTC, kukolev requested changes

2022-06-05 08:28 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        var film_id = filmStorage.addFilm(film);
Нарушение кодстайла: название переменных и полей должно быть выполнено в стиле camelCase.

2022-06-05 08:28 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/model/Like.java
> +    private int film_id;
Нарушение кодстайла: название переменных и полей должно быть выполнено в стиле camelCase.

2022-06-05 08:28 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/model/Like.java
> +    private int user_id;
Нарушение кодстайла: название переменных и полей должно быть выполнено в стиле camelCase.

2022-06-05 08:28 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        var mpa_id = resultSet.getInt("mpa_id");
Нарушение кодстайла: название переменных и полей должно быть выполнено в стиле camelCase.

2022-06-05 08:28 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sqlQuery = "insert into films(name, description, duration, release_date, mpa_id) values (?, ?, ?, ?, ?)";
Эту строку лучше выделить в константу. Тогда строка не будет каждый раз создаваться при вызове метода.

Аналогично нужно поправить в других методах класса.

2022-06-05 08:28 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        String sqlQuery = "insert into users(email, birthday, name, login) values (?, ?, ?, ?)";
Эту строку лучше выделить в константу. Тогда строка не будет каждый раз создаваться при вызове метода.

Аналогично нужно поправить в других методах класса.

2022-06-05 08:28 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +    public static Mpa G() {
Нарушение кодстайла: название методов должно быть выполнено в стиле camelCase.

Нарушение кодстайла: Название мет
ода лучше начинать с глагола, так назначение метода будет понятно сразу из названия. Нужно поправить.

Вообще этот метод лишний, т.к. используется только в тестах. Писать код в проекте только для нужд тестов это плохая практика, т.к. тесты не должны влиять на функциональность. Если очень нужен такой метод, то в тестах можно добавить утилитарный класс с таким методом.

2022-06-05 20:20 UTC, GlebInside commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        var mpa_id = resultSet.getInt("mpa_id");
Исправлено

2022-06-05 20:20 UTC, GlebInside commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sqlQuery = "insert into films(name, description, duration, release_date, mpa_id) values (?, ?, ?, ?, ?)";
Исправлено

2022-06-05 20:20 UTC, GlebInside commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        String sqlQuery = "insert into users(email, birthday, name, login) values (?, ?, ?, ?)";
Исправлено

2022-06-05 20:20 UTC, GlebInside commented on src/main/java/ru/yandex/practicum/filmorate/model/Like.java
> +    private int user_id;
Исправлено

2022-06-05 20:20 UTC, GlebInside commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +    public static Mpa G() {
Исправлено

2022-06-05 20:21 UTC, GlebInside commented on src/main/java/ru/yandex/practicum/filmorate/model/Like.java
> +    private int film_id;
Исправлено

2022-06-05 23:00 UTC, kukolev requested changes

2022-06-05 23:00 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/model/getMpa.java
> +public class getMpa {
Название класса начинается с глагола и с маленькой буквы. Это нарушение кодстайла. По моему не следовало менять название, предыдущее было лучше.

2022-06-05 23:26 UTC, GlebInside commented on src/main/java/ru/yandex/practicum/filmorate/model/getMpa.java
> +public class getMpa {
Исправлено

2022-06-05 23:26 UTC, GlebInside commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        var film_id = filmStorage.addFilm(film);
Исправлено

2022-06-06 15:41 UTC, kukolev approved these changes

2022-06-06 16:49 UTC, merged